INSERT INTO PERSON(name) VALUES('JAN');
INSERT INTO PERSON(name) VALUES('PAWEŁ');
INSERT INTO PERSON(name) VALUES('BARTEK');
INSERT INTO PERSON(name) VALUES('IGOR');
INSERT INTO PERSON(name) VALUES('MATEUSZ');