INSERT INTO event_task_statuses(EVENT_ID, TASK_STATUSES_ID)
VALUES (1, 1);
INSERT INTO event_task_statuses(EVENT_ID, TASK_STATUSES_ID)
VALUES (1, 2);
INSERT INTO event_task_statuses(EVENT_ID, TASK_STATUSES_ID)
VALUES (1, 3);
INSERT INTO event_task_statuses(EVENT_ID, TASK_STATUSES_ID)
VALUES (2, 4);
INSERT INTO event_task_statuses(EVENT_ID, TASK_STATUSES_ID)
VALUES (2, 5);
INSERT INTO event_task_statuses(EVENT_ID, TASK_STATUSES_ID)
VALUES (3, 6);
INSERT INTO event_task_statuses(EVENT_ID, TASK_STATUSES_ID)
VALUES (3, 7);