INSERT INTO person_task_statuses(PERSON_ID, TASK_STATUSES_ID) VALUES (1, 1);
INSERT INTO person_task_statuses(PERSON_ID, TASK_STATUSES_ID) VALUES (1, 2);
INSERT INTO person_task_statuses(PERSON_ID, TASK_STATUSES_ID) VALUES (1, 3);
INSERT INTO person_task_statuses(PERSON_ID, TASK_STATUSES_ID) VALUES (2, 4);
INSERT INTO person_task_statuses(PERSON_ID, TASK_STATUSES_ID) VALUES (3, 5);
INSERT INTO person_task_statuses(PERSON_ID, TASK_STATUSES_ID) VALUES (4, 6);
INSERT INTO person_task_statuses(PERSON_ID, TASK_STATUSES_ID) VALUES (5, 7);