INSERT INTO to_do_predefined(name)
values ('lista 1');
INSERT INTO to_do_predefined(name)
values ('lista 2');
INSERT INTO to_do_predefined(name)
values ('lista 3');
INSERT INTO to_do_predefined(name)
values ('lista 4');
INSERT INTO to_do_predefined(name)
values ('lista 5');
INSERT INTO to_do_predefined(name)
values ('lista 6');
INSERT INTO to_do_predefined(name)
values ('lista 1');